### ISSUE TITLE
Add ability to publish monitoring metrics

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#300]
As geokrety admin, I would like to monitor/graph the following
- incomming user,
- new ruchy entries,
- error reported
- database health
- ...

A mechanism like prometheus metrics + graf tool could be used

This issue will be considered as closed when a first real metric graphic will be available.

Attention point
- security issue (service access)
- performance: metric must not reduce geokrety service perf

@kumy / feel free to complete/reword *your* original idea ;)

**Comment by boly38** [comment]
*boly38 PoC/WIP branch* : `wip/metrics`
- seems Jimdo/prometheus_client_php is not working properly (memory issue on very first test)
- seems prometheus + pushgateway could be a better solution / wip 

@kumy do you see an objection to define thoses 2 new service in geokrety prod instance ?

````
    pushgateway:
        image: prom/pushgateway
    prometheus:
        image: prom/prometheus:v2.2.0-rc.0
````
(will push a fresh sample soon)
